name: gitAction
on: push
jobs:
    sshConn:
        name: SshConn
        runs-on: ubuntu-latest
        steps:
            - name: conn to remote ssh server
              uses: appleboy/ssh-action@v2
              with:
                host:  ${{secrets.HOST}}
                username: ${{secrets.Username}}
                port: ${{secrets.PORT}}
                key: ${{secrets.KEY}}
                script: whoami