name: gitAction

on: 
  push:
    branches: [main]
jobs:
    scpConn:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: conn with scp proto
              uses: appleboy/scp-action@v0.1.4
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH }}
                port: ${{ secrets.PORT }}
                source: "./"
                target: "./test"
                strip_components: 1
    startJob:
        needs: scpConn
        runs-on: ubuntu-latest
        steps:
        - name: conn to remote ssh server
          uses: appleboy/ssh-action@master
          env:
            SSH_KEY: ${{secrets.SSH_KEY}}
          with:
            host:  ${{secrets.HOST}}
            username: ${{secrets.USERNAME}}
            port: ${{secrets.PORT}}
            key: ${{secrets.SSH}}
            script: | 
              cd ./test 
              NODE_ENV=$SSH_KEY pm2 restart web-interface --update-env

                