name: gitAction

    
on: push
jobs:
    sshConn:
        runs-on: ubuntu-latest
        steps:
            - name: conn to remote ssh server
              uses: appleboy/ssh-action@master
              with:
                host:  ${{secrets.HOST}}
                username: ${{secrets.USERNAME}}
                port: ${{secrets.PORT}}
                key: ${{secrets.SSH}}a
                script: whoami
    sftpConn:
        runs-on: ubuntu-latest
        steps:
            - name: conn with sftp proto 
              uses: nicklasfrahm/scp-action@main
              with:
                host: ${{secrets.HOST}}
                username: ${{secrets.USERNAME}}
                key: ${{secrets.SSH}}
                fingerprint: "SHA256:CDZEXwbseYK6XliO7Jif+1vskhJjdrziP1U1oUZ2DUg"
                source: .
                target: ~/test/a
                direction: upload 