name: gitAction
on: push
jobs:
    sshConn:
        runs-on: ubuntu-latest
        steps:
            - name: conn to remote ssh server
              uses: appleboy/ssh-action@v1
              with:
                host:  ${{secrets.HOST}}
                username: ${{secrets.USERNAME}}
                port: ${{secrets.PORT}}
                key: ${{secrets.KEY}}
                script: whoami